<head>
    <title><?= (isset($title)) ? $title : 'Library Management System';?></title>
    <link rel="shortcut icon" href="AppRoot/Assets/Img/fav.png">
    <meta name="description" content="Library Management System" />
    <meta name="keywords" content="Library Management System, Books, Lend a book" />
    <link rel="stylesheet" type="text/css" href="AppRoot/Assets/CSS/styles.css" />
    <link rel="stylesheet" type="text/css" href="AppRoot/Assets/CSS/vendors/pikaday.css" />
    <script type="text/javascript" src="AppRoot/Assets/JS/vendors/pikaday.js"></script>
    <script type="text/javascript" src="AppRoot/Assets/JS/javascript.js"></script>
</head>