<div id="sidebar_container">
    <div class="sidebar">
        <div class="sidebar_item">
            <img src="AppRoot/Assets/Img/profile.jpg">
            <h3>Username: <?php echo $sessionUN; ?></h3>
            <h4>Name : <?php echo $sessionFNa . " " . $sessionSNa; ?></h4>
            <h5>Todays Date: <?php echo date('Y M d'); ?></h5>
        </div>
        <div class="sidebar_base"></div>
    </div>
</div>
